services:
  course-app:
    container_name: course-app
    build: .
    image: course-app:latest
    ports:
      - ${DOCKER_APP_PORT:-8081}:8080
    depends_on:
      course_db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://course_db:5432/${POSTGRES_DB:-course_app_db}
      - DB_USERNAME=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - DB_HOST=course_db
      - DB_PORT=5432
      - DB_NAME=${POSTGRES_DB:-course_app_db}
    networks:
      - spring-cloud-network

  course_db:
    container_name: course_db
    image: postgres
    ports:
      - ${DOCKER_DB_PORT:-5435}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-course_app_db}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - spring-cloud-network
volumes:
  db-data:
networks:
  spring-cloud-network:
    driver: bridge