spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/course_db
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: never
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8123
