server:
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:course_app_db}
    password: ${DB_PASSWORD:changeme}
#  jpa:
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org:
      springframework:
        web: ${LOG_LEVEL:info}
    uz:
      exadel: ${LOG_LEVEL:info}